# Generated by Django 2.2.12 on 2020-05-05 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200505_0413'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredienteEnHamburguesa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='hamburguesa',
            name='ingredientes',
            field=models.ManyToManyField(to='api.IngredienteEnHamburguesa'),
        ),
    ]
